export const RebirthTypes = {
  NoRebirth: 'ERebirthType::NoRebirth',
  AlwaysRebirth: 'ERebirthType::AlwaysRebirth',
  RebirthFullExplore: 'ERebirthType::RebirthFullExplore', // rebirth until cave is fully explored
  RebirthLater: 'ERebirthType::RebirthLater',
}

export const PikminColor = {
  Red: 'red',
  Yellow: 'yellow',
  Blue: 'blue',
  Purple: 'purple',
  White: 'white',
  Rock: 'rock',
  Wing: 'wing',
  Ice: 'ice',
  Glow: 'glow',
}

export const PikminSpawnState = {
  Sprouts: 'sprouts',
  Fighting: 'fighting',
  Idle: 'idle',
}

export const PikminColorBlueprintMap = {
  'GPikminRed_C': PikminColor.Red,
  'GPikminYellow_C': PikminColor.Yellow,
  'GPikminBlue_C': PikminColor.Blue,
  'GPikminPurple_C': PikminColor.Purple,
  'GPikminWhite_C': PikminColor.White,
  'GPikminRock_C': PikminColor.Rock,
  'GPikminWing_C': PikminColor.Wing,
  'GPikminIce_C': PikminColor.Ice,
  'GPikminPhoton_C': PikminColor.Glow,
}

export const PikminColorEnumMap = {
  "EPikminColor::Red": PikminColor.Red,
  "EPikminColor::Yellow": PikminColor.Yellow,
  "EPikminColor::Blue": PikminColor.Blue,
  "EPikminColor::Purple": PikminColor.Purple,
  "EPikminColor::White": PikminColor.White,
  "EPikminColor::Rock": PikminColor.Rock,
  "EPikminColor::Wing": PikminColor.Wing,
  "EPikminColor::Ice": PikminColor.Ice,
  "EPikminColor::Photon": PikminColor.Glow,
  "EPikminColor::Undef": PikminColor.Red,
  "EPikminColor::None": PikminColor.Red,
}

export const MarkerType = {
  // collectibles
  Treasure: 'treasure',
  CastawayNormal: 'castaway-normal',
  CastawayLeafling: 'castaway-leafling',
  Creature: 'creature',
  OnionFlarlic: 'onion-flarlic',
  OnionRed: 'onion-red',
  OnionYellow: 'onion-yellow',
  OnionBlue: 'onion-blue',
  OnionPurple: 'onion-purple',
  OnionWhite: 'onion-white',
  OnionRock: 'onion-rock',
  OnionWing: 'onion-wing',
  OnionIce: 'onion-ice',
  // pikmin
  PikminRed: 'pikmin-red',
  PikminYellow: 'pikmin-yellow',
  PikminBlue: 'pikmin-blue',
  PikminPurple: 'pikmin-purple',
  PikminWhite: 'pikmin-white',
  PikminRock: 'pikmin-rock',
  PikminWing: 'pikmin-wing',
  PikminIce: 'pikmin-ice',
  CandypopRed: 'candypop-red',
  CandypopYellow: 'candypop-yellow',
  CandypopBlue: 'candypop-blue',
  CandypopPurple: 'candypop-purple',
  CandypopWhite: 'candypop-white',
  CandypopRock: 'candypop-rock',
  CandypopWing: 'candypop-wing',
  CandypopIce: 'candypop-ice',
  // structures
  PileMaterials: 'pile-materials',
  StructureBridge: 'structure-bridge',
  StructureSlope: 'structure-slope',
  StructureValve: 'structure-valve',
  StructureWall: 'structure-wall',
  HazardSprinkler: 'hazardradial-sprinkler',
  // breakables
  BreakableHydrojelly: 'breakable-hydrojelly',
  BreakablePot: 'breakable-pot',
  BreakableKingcapnormal: 'breakable-kingcapnormal',
  BreakableSpotcapnormal: 'breakable-spotcapnormal',
  BreakableKingcappoison: 'breakable-kingcappoison',
  BreakableSpotcappoison: 'breakable-spotcappoison',
  MiscGroupdropmanager: 'misc-groupdropmanager',
  BreakableStraw: 'breakable-straw',
  BreakableIcebox: 'breakable-icebox',
  FirepitLit: 'firepit-lit',
  FirepitUnlit: 'firepit-unlit',
  BreakableCrystal: 'breakable-crystal',
  // items
  BreakableMound: 'breakable-mound',
  BreakableEgg: 'breakable-egg',
  MiscBomb: 'miscitem-bomb',
  MiscIcebomb: 'miscitem-icebomb',
  MiscSpicy: 'miscitem-spicy', // not an actual map marker, but is a drop marker
  MiscSpiderwort: 'misc-spiderwort',
  // hazards
  HazardSpoutFire: 'hazardspout-fire',
  HazardSpoutElectric: 'hazardspout-electric',
  HazardSpoutWater: 'hazardspout-water',
  HazardSpoutPoison: 'hazardspout-poison',
  HazardSpoutIce: 'hazardspout-ice',
  HazardSpoutBubble: 'hazardspout-bubble',
  HazardFloorfire: 'hazardradial-floorfire',
  HazardCharcoal: 'hazardmisc-charcoal',
  HazardFloormushroom: 'hazardradial-floormushroom',
  // shortcuts
  ShortcutClipboardhigh: 'shortcut-clipboardhigh',
  ShortcutClipboardlow: 'shortcut-clipboardlow',
  ShortcutPushbag: 'shortcut-pushbag',
  ShortcutPushboxcardboard: 'shortcut-pushboxcardboard',
  ShortcutPushboxmetal: 'shortcut-pushboxmetal',
  ShortcutRoot: 'shortcut-root',
  ShortcutStringup: 'shortcut-stringup',
  ShortcutStringdown: 'shortcut-stringdown',
  RidableGeyser: 'ridable-geyser',
  RidableZipline: 'ridable-zipline',
  TunnelAny: 'tunnel-any',
  TunnelCaptain: 'tunnel-captain',
  TunnelOatchi: 'tunnel-oatchi',
  PlatformBounce: 'platform-bounceshroom',
  PlatformCharge: 'platform-chargeshroom',
  RidableMovefloor: 'ridable-movefloor',
  // gates
  GateBomb: 'gate-bomb',
  GateCrystal: 'gate-crystal',
  GateDirt: 'gate-dirt',
  GateElectric: 'gate-electric',
  GateIce: 'gate-ice',
  GateNumbered: 'gate-numbered',
  ShortcutSquashbag: 'shortcut-squashbag',
  // switchables
  SwitchConveyor: 'switchable-conveyor',
  SwitchFan: 'switchable-fan',
  SwitchFenceiron: 'switchable-fenceiron',
  SwitchFencenormal: 'switchable-fencenormal',
  SwitchSingle: 'switchable-singleswitch',
  SwitchDouble: 'switchable-doubleswitch',
  // locations
  BaseOnion: 'base-onion',
  BaseBeagle: 'base-beagle',
  CaveEntrance: 'cave-entrance',
  CaveExit: 'cave-exit',
  CaveChallenge: 'cave-challenge',
  CaveBattle: 'cave-battle',
  // water
  WaterWater: 'water-water',
  WaterSwamp: 'water-swamp',
  SwitchDrain: 'switchable-drain',
  // misc
  MiscPullrope: 'misc-pullrope',
  MiscStick: 'misc-stick',
  MiscIcicle: 'misc-icicle',
  MiscHoney: 'miscitem-honey',
  MiscPellet: 'misc-pellet',
  // night
  NightLumiknoll: 'night-lumiknoll',
  NightTricknoll: 'night-tricknoll',
  PileGlowpellets: 'pile-glowpellets',
}

export const InfoType = {
  Treasure: 'treasure',
  Castaway: 'castaway',
  Creature: 'creature',
  Onion: 'onion',
  Pikmin: 'pikmin',
  Candypop: 'candypop',
  Structure: 'structure',
  Pile: 'pile',
  Breakable: 'breakable',
  Firepit: 'firepit',
  Hazard: 'hazard',
  Shortcut: 'shortcut',
  Ridable: 'ridable',
  Platform: 'platform',
  Tunnel: 'tunnel',
  Gate: 'gate',
  Switchable: 'switchable',
  Base: 'base',
  Cave: 'cave',
  Water: 'water',
  Misc: 'misc',
  Night: 'night',
}
